name: run main.py

on:
  schedule:
    - cron: '0,15,30,45 * * * *' # run exactly every 15 minutes
  repository_dispatch:
    types: [resume_schedule]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: execute_script # Ensure the execute_script job is completed before running this job
    env:
      # Set the environment variable based on the output of the execute_script print statement
        REVENUE_THRESHOLD_MET: ${{ needs.execute_script.outputs.revenue_threshold_met }}

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to GitHub runner
        with: 
          node-version: '16.15.0'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Save Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          
      - name: execute py script # run main.py
        id: execute_script
        run: python src/script.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          # Amazon credentials
          SP_API_REFRESH_TOKEN: ${{ secrets.SP_API_REFRESH_TOKEN }}
          LWA_APP_ID: ${{ secrets.LWA_APP_ID }}
          LWA_CLIENT_SECRET: ${{ secrets.LWA_CLIENT_SECRET }}
          SP_API_ACCESS_KEY: ${{ secrets.SP_API_ACCESS_KEY }}
          SP_API_SECRET_KEY: ${{ secrets.SP_API_SECRET_KEY }}
          SP_API_ROLE_ARN: ${{ secrets.SP_API_ROLE_ARN }}
          # Gmail credentials
          GMAIL_USERNAME: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          
      - name: Check revenue threshold and pause schedule if needed
        if: ${{ env.REVENUE_THRESHOLD_MET == 'true' }}
        run: |
          echo "Pause the schedule until midnight if revenue threshold is met."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/jhalzel/amz-monitor_test/actions/workflows/pause.yaml/dispatches \
              -d '{"ref":"main", "inputs": {"revenue_threshold_met": "true"}}'

      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main
